<div style="width:100% !important;border-radius:3px;max-width:600px !important;margin:0 auto;color:#171717;;font-family:Arial,sans-serif;font-size:14px;line-height:1.429;background-color:  #f3f6f7;box-shadow: 0px 1px 2px 1px #d6dde1;">
    <table cellpadding="0" cellspacing="0" width="100%"
           style="border-collapse:collapse;background-color:#f5f5f5;border-collapse:collapse">
        <thead style="background-color: #fff;border-bottom: 1px solid #d6dde1;text-align: left;">
        </thead>
        <tbody>
            <tr>
                <td style="padding:0px;border-collapse:collapse;padding:0 20px">
                    <table cellspacing="0" cellpadding="0" border="0" width="100%" style="border-collapse:collapse;border-spacing:0;border-collapse:separate">
                        <tbody>
                        <tr>
                            <td style="border-radius:0 0 3px 3px;padding:16px 20px;border-collapse:collapse;color:#8899aa;font-size:12px;line-height:18px;font-family:Arial,sans-serif;text-align:center;">
                              <img src="http://storage.aqilix.xyz/aqilix/aqilix-bright-256-80.png" width="200" height="48" alt="Aqilix"  title="Aqilix">
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:0px;border-collapse:collapse;padding:0 20px">
                    <table cellspacing="0" cellpadding="0" border="0" width="100%"
                           style="border-collapse:collapse;border-spacing:0;border-collapse:separate">
                        <tbody>
                        <tr>
                            <td style="border-collapse:collapse;border:1px solid #d6dde1;padding: 16px 30px;background-color:#fff;">
                                <table cellspacing="0" cellpadding="0" border="0" width="100%" style="border-collapse:collapse;font-family:Arial,sans-serif;font-size:14px;line-height:20px">
                                    <tbody>
                                    <tr>
                                        <td style="padding:0px;border-collapse:collapse;">
                                            <p style="margin:0 0 20px 0;">
                                                Hi,<br /><br />
                                                Congratulation, your account has been activated!<br />
                                            </p>
                                            <p style="margin:0 0 20px 0;">
                                                Cheers,<br /><br />
                                                The team at Aqilix
                                            </p>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td style="padding:0px;border-collapse:collapse;padding:0 20px">
                    <table cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;width:100%">
                        <tbody>
                        <tr>
                            <td style="border-radius:0 0 3px 3px;padding:16px 20px;border-collapse:collapse;color:#8899aa;font-size:12px;line-height:18px;font-family:Arial,sans-serif">
                                You are receiving this email because you are an Aqilix user. If you believe that you shouldn't have been signed up, please <a href="<?php echo $contactUsUrl ?>" target="_blank" style="color: #3388cc;text-decoration: none">contact us</a>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
</div>